# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import restaurants.validators


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantlocations',
            name='category',
            field=models.CharField(blank=True, max_length=128, null=True, validators=[restaurants.validators.validate_category]),
        ),
    ]
