# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 06:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_auto_20170725_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Restaurant City'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name_plural': 'Restaurant States'},
        ),
    ]
