# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_restaurantlocations_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantCuisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Restaurant Cuisine',
            },
        ),
    ]
