# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_restaurantcuisine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': '02 Restaurant City'},
        ),
        migrations.AlterModelOptions(
            name='restaurantcuisine',
            options={'verbose_name_plural': '03 Restaurant Cuisine'},
        ),
        migrations.AlterModelOptions(
            name='restaurantlocations',
            options={'ordering': ['-updated'], 'verbose_name_plural': '04 Restaurant Location'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name_plural': '01 Restaurant States'},
        ),
    ]
