# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_auto_20170731_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantHighlights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_parking', models.CharField(blank=True, choices=[('available', 'available'), ('not available', 'not available')], max_length=128, null=True)),
                ('home_delivery', models.CharField(blank=True, choices=[('available', 'available'), ('not available', 'not available')], max_length=128, null=True)),
                ('take_away', models.CharField(blank=True, choices=[('available', 'available'), ('not available', 'not available')], max_length=128, null=True)),
                ('cards', models.CharField(blank=True, choices=[('accepted', 'accepted'), ('not accepted', 'not accepted')], max_length=128, null=True)),
                ('ac', models.CharField(blank=True, choices=[('available', 'available'), ('not available', 'not available')], max_length=128, null=True)),
            ],
            options={
                'verbose_name_plural': '05 Restaurant Details',
            },
        ),
        migrations.AddField(
            model_name='restaurantlocations',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantlocations',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restauranthighlights',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.RestaurantLocations'),
        ),
    ]
