# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_auto_20170719_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': '01 Menu Item Category',
            },
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-updated', '-timestamp'], 'verbose_name_plural': '02 Menu Item'},
        ),
        migrations.AddField(
            model_name='item',
            name='course',
            field=models.CharField(blank=True, choices=[('All', 'All'), ('Main Course', 'Main Course'), ('Side Dish', 'Side Dish'), ('Drinks', 'Drinks'), ('Juice', 'Juice'), ('Snacks', 'Snacks'), ('Ice Creams', 'Ice Creams')], default='All', max_length=50, null=True),
        ),
    ]
