# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_auto_20170731_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menus.ItemCategory'),
            preserve_default=False,
        ),
    ]
