# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_item_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
